// Authentication step modules for clean separation of concerns
export { AuthenticationStepExecutor } from './AuthenticationStepExecutor'
export { AuthenticationValidator } from './AuthenticationValidator'
export type { ValidationContext } from './AuthenticationValidator'
export { FirebaseAuthenticator } from './FirebaseAuthenticator'
export type { SignatureVerificationContext } from './FirebaseAuthenticator'
export { MessageGenerator } from './MessageGenerator'
export type { GeneratedAuthMessage } from './MessageGenerator'
export { SignatureHandler } from './SignatureHandler'
export type { SignatureContext } from './SignatureHandler'
